### ISSUE TITLE
new feature add smart config switch

### ISSUE THREAD

**Issue by AlexanderGoerlich** [senseexcel/ser-web-management#353]
[HUB] , [E-Mail], [Folder], [static (0), dynamic(1)], [task (0)]

![image](https://user-images.githubusercontent.com/13659581/64960320-5cc95000-d893-11e9-889b-1769bde5b8ec.png)

Idea is a smart config settings directly by adding this and show up an overview about this settings. enable and disable functions are be nice... --> background when editing they show up or dont shows up ... settings section. 
![image](https://user-images.githubusercontent.com/13659581/65878173-b5b5df80-e38d-11e9-9722-32c323ef84e8.png)

**Comment by r-hannuschka** [comment]
As i understand this right this is like ( activate Export HUB / Email but deactivate FILE ). If i now open the Report Edit View file settings will not shown in my view anymore until i activate this again.

What if i decide i want add File i have to go back and activate this Setting ?

This is more a configuration for edit mode not for the meta informations of a report  ( name, short description ) which was only added to find the report more easy and not watch into every report for which app will used what selections etc. 

What you want is a configuration / settings which affects the view of edit directly and this should , in my opinion, not placed into smc meta data since this is very special for smc. 
So yes i could add this to meta informations but i dont like it since this is the wrong place for that, and not affects the report himself only the smc.

But before we do this we have to talk about that feature, thats the point i have to save all settings into the report script (which will grow up) and what if we decide to enable a section if we currently edit one report, so have we to go out and enable it again ?

**Comment by AlexanderGoerlich** [comment]
:-)
