### ISSUE TITLE
single quotes are missing in target Property of file section

### ISSUE THREAD

**Issue by thomashaenig** [senseexcel/ser-web-management#355]
![image](https://user-images.githubusercontent.com/17725886/65039330-46ce9480-d952-11e9-9fbd-c456cdcc5d5f.png)

**Comment by r-hannuschka** [comment]
I cant add some single quotes to this if i do this it will add double quotes.

```json
file: {
   target: "'FILEPATH'"
   ...
```

I could tell the HJSON it should add quotes arround all values, but then Human JSON is not really required any more since the only advantage we will have now is missing all colons. 
Even escape white spaces with **\ ** or **\s** will not work since this is a simple string and not nothing special.

On the other side in only write a configuration, so what u enter is the result maybe we have take a look on the side where the configuration will consumed what happens there to get more informations about this.

**Comment by thomashaenig** [comment]
@AlexanderGoerlich we are not able to reproduce this issue the following is working. please check this again, when working the issue will be closed.
![image](https://user-images.githubusercontent.com/17725886/65242055-6944e700-dae5-11e9-80ff-8ff3b3633250.png)
