### ISSUE TITLE
app crash, please check

### ISSUE THREAD

**Issue by thomashaenig** [senseexcel/ser-web-management#363]
when importing reporting app (app from other system, so id is incorrect) -> SMC is craching

**Comment by r-hannuschka** [comment]
Issue seams allready be solved in SMC.

Workflow: 

1. Download Demo App and import this in QMC
2. Open in SMC, this will show an appid and if you try to connect you get a message that you cant connect to app since this is not found.

The more greater issue is maybe on SER, since configuration holds a wrong app id.

Maybe we could add a simple message in SMC to show User "hey there is no app found with this will not work" @see #365
