### ISSUE TITLE
show warn msg on top when not connected to application

### ISSUE THREAD

**Issue by thomashaenig** [senseexcel/ser-web-management#379]

**Comment by r-hannuschka** [comment]
i would put this below, since the error app not found is on same position

Warning not connected:

![image](https://user-images.githubusercontent.com/25415574/68215251-3300ef80-ffdf-11e9-9a1b-bf33cf6638b6.png)

Error unknown App

![image](https://user-images.githubusercontent.com/25415574/68215351-5deb4380-ffdf-11e9-8dd0-f04bc25b57f1.png)

So both are on same position. Or we could both on top
