### ISSUE TITLE
[FR] - SER QMC Interface set filter (sele) only Bookmark and Static , Dynamic (loop)

### ISSUE THREAD

**Issue by AlexanderGoerlich** [senseexcel/ser-web-management#52]
please ask mossbeard... for selections
```
# Template Settings
template: 
{
	input: content:///ExecutiveDashboard.xlsx
	output: ='Report_'&only(Region)&'_'&max([Fiscal Year])&'.pdf'
		
	selections:[
        {
            type: static
            name: Fiscal Year
            values: =[Fiscal Year]=(Year(ToDay())-4)
        }
        {
            type: dynamic
            name: Region
        }
        {
      		type: static
      		objectType: bookmark
      		values: NameOfTheBookmark
    	}
	]
  }

````

**Comment by AlexanderGoerlich** [comment]
# create an easy input section with a dropdown and inputfield

**Comment by r-hannuschka** [comment]
This should reworked, since i have a single input field, but the truth is there can be many schemaEvents and the question is which one will be edited currently. Currently i dont know how many Schema Events are really existing and which one was created by webapp.

Currently it would be better to edit / create this tasks Time Events in the QMC  directly to be sure nothing will be overriden.
